import { defineConfig } from 'tsup';

export default defineConfig([
  {
    entry: ['src/index.ts'],
    format: ['esm', 'cjs'],
    dts: true,
    sourcemap: false,
    clean: true,
    splitting: false,
    treeshake: true,
    minify: true,
    target: 'es2020',
  },
  {
    entry: { browser: 'src/browser.ts' },
    format: ['esm'],
    dts: false,
    sourcemap: false,
    clean: false,
    splitting: false,
    treeshake: true,
    minify: true,
    target: 'es2020',
    noExternal: ['ai', '@ai-sdk/*'],
  },
  {
    entry: { 'browser-global': 'src/browser-global.ts' },
    format: ['iife'],
    globalName: 'TellSDKGlobal',
    dts: false,
    sourcemap: false,
    clean: false,
    splitting: false,
    treeshake: true,
    minify: true,
    target: 'es2020',
    noExternal: ['ai', '@ai-sdk/*'],
  },
]);
